package com.test.res.datasource.repository;

import com.test.res.datasource.entity.TestEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.querydsl.QuerydslPredicateExecutor;
import org.springframework.stereotype.Repository;

/**
* Generated by Spring Data Generator on 11/01/2019
*/
@Repository
public interface TestEntityRepository extends JpaRepository<TestEntity, Integer>, JpaSpecificationExecutor<TestEntity>, QuerydslPredicateExecutor<TestEntity> {

}
